name: Build Windows Executable and Release

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile --windowed discord_overlay.py

      - name: Move executable to releases folder
        run: |
          move dist\discord_overlay-1.0.exe releases\discord_overlay-1.0.exe

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Add Windows executable (version 1.0)"
          git push origin main --force